apiVersion: v1
kind: Service
metadata:
  name: codimd-svc
  namespace: codimd
spec:
  selector:
      app: codimd
  ports:
    - name: codimd-svc
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30017
  type: NodePort
