apiVersion: v1
kind: Service
metadata:
  name: codidb-svc
  namespace: codimd
spec:
  selector:
      app: codidb
  ports:
    - name: codidb-svc
      protocol: TCP
      port: 5432
      targetPort: 5432
